"""change contacts_json to jsonb

Revision ID: 08846da31ccd
Revises: 6d883e368d67
Create Date: 2026-03-01 13:43:03.145326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08846da31ccd'
down_revision: Union[str, Sequence[str], None] = '6d883e368d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'org_units', 'employees', ['manager_employee_id'], ['id'])
    op.alter_column(
        'providers',
        'contacts_json',
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(),
        existing_nullable=True,
        postgresql_using='contacts_json::jsonb'
    )
    op.alter_column('training_sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('providers', 'contacts_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'org_units', type_='foreignkey')
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
