"""updated training_session

Revision ID: 09d937330433
Revises: 4ce190d27a44
Create Date: 2026-03-07 23:58:39.689015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d937330433'
down_revision: Union[str, Sequence[str], None] = '4ce190d27a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'org_units', 'employees', ['manager_employee_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_units', type_='foreignkey')
    # ### end Alembic commands ###
