"""trainer email unique

Revision ID: 5adf895dbbc0
Revises: f80b5eda408b
Create Date: 2026-03-06 23:35:31.573980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adf895dbbc0'
down_revision: Union[str, Sequence[str], None] = 'f80b5eda408b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'org_units', 'employees', ['manager_employee_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.alter_column('trainers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_trainers_email', table_name='trainers')
    op.create_index(op.f('ix_trainers_email'), 'trainers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainers_email'), table_name='trainers')
    op.create_index('ix_trainers_email', 'trainers', ['email'], unique=False)
    op.alter_column('trainers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'org_units', type_='foreignkey')
    # ### end Alembic commands ###
