"""employee orgubit fix

Revision ID: 9a06de9ea20c
Revises: d78bc68a4291
Create Date: 2026-03-02 23:49:10.310801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a06de9ea20c'
down_revision: Union[str, Sequence[str], None] = 'd78bc68a4291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'org_units', 'employees', ['manager_employee_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_units', type_='foreignkey')
    # ### end Alembic commands ###
