"""change contactz in organization

Revision ID: 9f28dc362e63
Revises: 08846da31ccd
Create Date: 2026-03-01 13:50:54.393761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f28dc362e63'
down_revision: Union[str, Sequence[str], None] = '08846da31ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'organizations',
        'contacts_json',
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(),
        existing_nullable=True,
        postgresql_using='contacts_json::jsonb'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'contacts_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
